### ISSUE TITLE
what are the .txt files for each video?

### ISSUE THREAD

**Issue by nyck33** [gKouros/intro-to-cv-ud810#1]
they look like coordinates but not sure what format it's in.

**Comment by gkouros** [comment]
They are x, y, width, height of the starting bounding box, where x,y is the upper left corner of the box.
https://github.com/gkouros/intro-to-cv-ud810/blob/efede1b680388bc229f2dab53e0e13f9ee15c4cd/ps6_python/msl_pf_tracker_demo.py#L23

**Comment by nyck33** [comment]
sorry @gkouros , I had not gone through before issuing.

it looks like the problems sets are no longer on the Udacity course so can you also tell me what the params are here:

```
def naive_pf_tracker_demo(videofile, textfile, frames_to_save=[], infix='a',
                          play_video=True, num_particles=100, dimensions=2,
                          control=10, sim_std=20, alpha=0):
```
I'm trying to track player, racket or the tennis ball in a match between Federer and Nadal.
Frame 72 is when the actual tennis begins and I have 
                             Nadal         racket          ball
xy top left             (689,440)    (670,683)     (677,474)
xy bottom right     (731,581)    (456, 482)     (685,481)

video link:  https://drive.google.com/file/d/1ylsy0Y6yYgYtok3CwdU8Q6yfYOaVI-gT/view?usp=sharing

Any help you can provide is appreciated.  Right now, it won't pick up any of the three so the placement of the bounding box and particles is a bit random.

**Comment by gkouros** [comment]
frames_to_save: list containing the indices of the frames to be saved
infix: string to add to the names of the saved frames
dimensions: the number of states of each particle
control: std of normal distribution of new particles being generated
sim_std: deprecated
alpha: parameter of adaptive model update. Use zero for using a fixed template and greater than zero otherwise.

**Comment by nyck33** [comment]
thanks.
